//
// Created by 刘鹏 on 2019/12/29.
//

#ifndef CPLUSPLUSSTLBYLIUPENG_ABOUTSTRLEN_H
#define CPLUSPLUSSTLBYLIUPENG_ABOUTSTRLEN_H
#include<cstring>
void palyInStrlen();


#endif //CPLUSPLUSSTLBYLIUPENG_ABOUTSTRLEN_H
